export type Product = {
  id: string
  name: string
  slug: string
  price: number
  originalPrice?: number
  discount?: number
  image: string
  images?: string[] // Added multiple images support for product detail view
  category: string
  description: string
  sizes: string[]
  colors: string[]
  rating: number
  reviews: number
  inStock: boolean
  mode: "men" | "women" | "kids"
}

export const products: Product[] = [
  // Men's Products
  {
    id: "1",
    name: "Classic Oxford Shirt",
    slug: "classic-oxford-shirt",
    price: 1299,
    originalPrice: 1999,
    discount: 35,
    image: "/men-s-blue-oxford-button-down-shirt.jpg",
    images: ["/men-s-blue-oxford-button-down-shirt.jpg", "/men_products/classic-flex-casual-shirt.jpg"], // Added multiple images support for product detail view
    category: "Shirts",
    description: "Premium cotton oxford shirt with button-down collar. Perfect for both casual and formal occasions.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Blue", "White", "Light Blue"],
    rating: 4.5,
    reviews: 128,
    inStock: true,
    mode: "men",
  },
  {
    id: "2",
    name: "Slim Fit Denim Jeans",
    slug: "slim-fit-denim-jeans",
    price: 1799,
    originalPrice: 2499,
    discount: 28,
    image: "/men_products/mens-levis-511-slim-fit-jeans-mid-wash-size-30-32-genuine-e8.jpg",
    images: ["/men_products/mens-levis-511-slim-fit-jeans-mid-wash-size-30-32-genuine-e8.jpg", "/men_products/Level Jeans™ _ Organic Denim _ Men's Slim Straight Fit _ Blue Classic.jpg"], // Added multiple images support for product detail view
    category: "Jeans",
    description: "Comfortable stretch denim with modern slim fit. Features classic 5-pocket styling.",
    sizes: ["28", "30", "32", "34", "36"],
    colors: ["Dark Blue", "Black", "Light Blue"],
    rating: 4.7,
    reviews: 256,
    inStock: true,
    mode: "men",
  },
  {
    id: "3",
    name: "Leather Jacket",
    slug: "leather-jacket",
    price: 4999,
    image: "/men_products/download.jpg",
    images: ["/men_products/download.jpg", "/men_products/fall-leather-jacket-black-aesthetic.jpg"], // Added multiple images support for product detail view
    category: "Jackets",
    description: "Genuine leather jacket with quilted shoulders. Classic biker style with multiple pockets.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Brown"],
    rating: 4.8,
    reviews: 89,
    inStock: true,
    mode: "men",
  },
  {
    id: "4",
    name: "Sports Running Shoes",
    slug: "sports-running-shoes",
    price: 2499,
    originalPrice: 3499,
    discount: 29,
    image: "/white-athletic-running-shoes-sneakers.jpg",
    images: ["/white-athletic-running-shoes-sneakers.jpg", "/men_products/nike-sportswear-womens-v2k-run-summit-white-metallic-silver-trainers-womens-shoes-pro-direct-soccer.jpg"], // Added multiple images support for product detail view
    category: "Shoes",
    description: "Lightweight running shoes with cushioned sole. Breathable mesh upper for maximum comfort.",
    sizes: ["7", "8", "9", "10", "11"],
    colors: ["White", "Black", "Grey"],
    rating: 4.6,
    reviews: 342,
    inStock: true,
    mode: "men",
  },
  {
    id: "5",
    name: "Casual Polo Shirt",
    slug: "casual-polo-shirt",
    price: 899,
    originalPrice: 1299,
    discount: 31,
    image: "/men-s-green-polo-shirt-casual.jpg",
    images: ["/men-s-green-polo-shirt-casual.jpg", "/men_products/polo_tshirts.jpg"], // Added multiple images support for product detail view
    category: "Shirts",
    description: "Breathable cotton polo with ribbed collar and cuffs. Perfect for casual weekends.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Green", "Navy", "White", "Grey"],
    rating: 4.4,
    reviews: 176,
    inStock: true,
    mode: "men",
  },
  {
    id: "6",
    name: "Chino Trousers",
    slug: "chino-trousers",
    price: 1599,
    originalPrice: 2199,
    discount: 27,
    image: "/men-s-beige-chino-pants-trousers.jpg",
    images: ["/men-s-beige-chino-pants-trousers.jpg", "/men_products/permanent-designs-obsessively-refined.jpg"], // Added multiple images support for product detail view
    category: "Trousers",
    description: "Classic fit chino trousers in premium cotton twill. Versatile style for work or casual wear.",
    sizes: ["28", "30", "32", "34", "36", "38"],
    colors: ["Beige", "Navy", "Black", "Olive"],
    rating: 4.6,
    reviews: 198,
    inStock: true,
    mode: "men",
  },
  {
    id: "7",
    name: "Hooded Sweatshirt",
    slug: "hooded-sweatshirt",
    price: 1399,
    image: "/men-s-grey-hoodie-sweatshirt.jpg",
    images: ["/men-s-grey-hoodie-sweatshirt.jpg", "/men_products/cozy-everyday-essential-mens-pullover-hoodie-big-tall-available.jpg"], // Added multiple images support for product detail view
    category: "Hoodies",
    description: "Cozy fleece hoodie with kangaroo pocket. Perfect layering piece for cooler days.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Grey", "Black", "Navy", "Maroon"],
    rating: 4.7,
    reviews: 289,
    inStock: true,
    mode: "men",
  },
  {
    id: "8",
    name: "Formal Blazer",
    slug: "formal-blazer",
    price: 3999,
    originalPrice: 5999,
    discount: 33,
    image: "/men-s-navy-blue-formal-blazer-suit-jacket.jpg",
    images: ["/men-s-navy-blue-formal-blazer-suit-jacket.jpg", "/men_products/classy-meets-contemporary-21-stylish-suits-every-modern-man-needs.jpg"], // Added multiple images support for product detail view
    category: "Blazers",
    description: "Tailored fit blazer in premium wool blend. Two-button front with notch lapels.",
    sizes: ["38", "40", "42", "44", "46"],
    colors: ["Navy", "Charcoal", "Black"],
    rating: 4.9,
    reviews: 134,
    inStock: true,
    mode: "men",
  },
  {
    id: "9",
    name: "Graphic T-Shirt",
    slug: "graphic-t-shirt",
    price: 699,
    originalPrice: 999,
    discount: 30,
    image: "/men_products/T-Shirt-design.jpg",
    images: ["/men_products/T-Shirt-design.jpg", "/men_products/download-1.jpg"], // Added multiple images support for product detail view
    category: "T-Shirts",
    description: "Comfortable cotton t-shirt with bold graphic print. Relaxed fit for everyday wear.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "White", "Grey"],
    rating: 4.3,
    reviews: 412,
    inStock: true,
    mode: "men",
  },
  {
    id: "10",
    name: "Leather Belt",
    slug: "leather-belt",
    price: 799,
    image: "/men-s-brown-leather-belt-buckle.jpg",
    images: ["/men-s-brown-leather-belt-buckle.jpg", "/men_products/two-layer-leather-belt-thick-brush-buckle-brown-125cm.jpg"], // Added multiple images support for product detail view
    category: "Accessories",
    description: "Genuine leather belt with classic buckle. Essential accessory for formal and casual looks.",
    sizes: ["32", "34", "36", "38", "40"],
    colors: ["Brown", "Black", "Tan"],
    rating: 4.5,
    reviews: 267,
    inStock: true,
    mode: "men",
  },

  // Women's Products
  {
    id: "11",
    name: "Floral Maxi Dress",
    slug: "floral-maxi-dress",
    price: 1899,
    originalPrice: 2999,
    discount: 37,
    image: "/women-s-pink-floral-maxi-dress-summer.jpg",
    images: ["/women-s-pink-floral-maxi-dress-summer.jpg", "/women_products/house-of-cb-tallulah-floral-cotton-blend-sundress-white-pink-floral-nordstrom-size-x-large.jpg"], // Added multiple images support for product detail view
    category: "Dresses",
    description: "Elegant floral print maxi dress with flowing silhouette. Perfect for summer occasions.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Pink", "Blue", "Yellow"],
    rating: 4.7,
    reviews: 198,
    inStock: true,
    mode: "women",
  },
  {
    id: "12",
    name: "Silk Blouse",
    slug: "silk-blouse",
    price: 1599,
    image: "/women-s-white-silk-blouse-elegant.jpg",
    images: ["/women-s-white-silk-blouse-elegant.jpg", "/women_products/women-plain-front-button-long-sleeve-casual-top-minimalist-hollowed-costumes-thanksgiving-women-outfit-princess-women-costume-greek-goddess-costume-cowgirl-women-outfits-costume.jpg"], // Added multiple images support for product detail view
    category: "Tops",
    description: "Luxurious silk blouse with delicate detailing. Versatile piece for office or evening wear.",
    sizes: ["XS", "S", "M", "L"],
    colors: ["White", "Cream", "Blush"],
    rating: 4.9,
    reviews: 143,
    inStock: true,
    mode: "women",
  },
  {
    id: "13",
    name: "High-Waist Skinny Jeans",
    slug: "high-waist-skinny-jeans",
    price: 1699,
    originalPrice: 2199,
    discount: 23,
    image: "/women-s-black-high-waist-skinny-jeans.jpg",
    images: ["/women-s-black-high-waist-skinny-jeans.jpg", "/women_products/high-waist-stretch-skinny-jeans-sleek-pencil-fit-modern-style-blue-l.jpg"], // Added multiple images support for product detail view
    category: "Jeans",
    description: "Flattering high-waist skinny jeans with stretch comfort. Modern fit with classic styling.",
    sizes: ["24", "26", "28", "30", "32"],
    colors: ["Black", "Dark Blue", "Grey"],
    rating: 4.6,
    reviews: 287,
    inStock: true,
    mode: "women",
  },
  {
    id: "14",
    name: "Designer Handbag",
    slug: "designer-handbag",
    price: 3999,
    image: "/women-s-beige-leather-designer-handbag.jpg",
    images: ["/women-s-beige-leather-designer-handbag.jpg", "/women_products/the-best-designer-bags-to-invest-in-2025-from-luxe-with-love.jpg"], // Added multiple images support for product detail view
    category: "Accessories",
    description: "Premium leather handbag with gold hardware. Spacious interior with multiple compartments.",
    sizes: ["One Size"],
    colors: ["Beige", "Black", "Brown"],
    rating: 4.8,
    reviews: 156,
    inStock: true,
    mode: "women",
  },
  {
    id: "15",
    name: "Knit Cardigan",
    slug: "knit-cardigan",
    price: 1299,
    originalPrice: 1799,
    discount: 28,
    image: "/women-s-cream-knit-cardigan-sweater.jpg",
    images: ["/women-s-cream-knit-cardigan-sweater.jpg", "/women_products/crochet-charms-toys-and-coasters.jpg"], // Added multiple images support for product detail view
    category: "Sweaters",
    description: "Cozy knit cardigan with button closure. Perfect layering piece for transitional weather.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Cream", "Grey", "Burgundy", "Navy"],
    rating: 4.6,
    reviews: 223,
    inStock: true,
    mode: "women",
  },
  {
    id: "16",
    name: "Formal Pencil Skirt",
    slug: "formal-pencil-skirt",
    price: 1199,
    image: "/women_products/pencil-skirt-business-casual-outfit.jpg",
    images: ["/women_products/pencil-skirt-business-casual-outfit.jpg", "/women_products/download-2.jpg"], // Added multiple images support for product detail view
    category: "Skirts",
    description: "Classic pencil skirt in stretch fabric. Professional silhouette perfect for the office.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Grey"],
    rating: 4.5,
    reviews: 189,
    inStock: true,
    mode: "women",
  },
  {
    id: "17",
    name: "Casual Tank Top",
    slug: "casual-tank-top",
    price: 599,
    originalPrice: 899,
    discount: 33,
    image: "/women_products/michael-stars-white-sleeveless-tank-top-pink-white-size-os.jpg",
    images: ["/women_products/michael-stars-white-sleeveless-tank-top-pink-white-size-os.jpg", "/women_products/download-3.jpg"], // Added multiple images support for product detail view
    category: "Tops",
    description: "Essential cotton tank top with scoop neck. Perfect basics for layering or standalone wear.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["White", "Black", "Grey", "Pink"],
    rating: 4.4,
    reviews: 567,
    inStock: true,
    mode: "women",
  },
  {
    id: "18",
    name: "Evening Gown",
    slug: "evening-gown",
    price: 4999,
    originalPrice: 7999,
    discount: 38,
    image: "/women_products/Dress.jpg",
    images: ["/women_products/Dress.jpg", "/women_products/download-4.jpg"], // Added multiple images support for product detail view
    category: "Dresses",
    description: "Stunning floor-length evening gown with elegant draping. Perfect for special occasions.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Red", "Black", "Navy", "Emerald"],
    rating: 4.9,
    reviews: 98,
    inStock: true,
    mode: "women",
  },
  {
    id: "19",
    name: "Ankle Boots",
    slug: "ankle-boots",
    price: 2499,
    image: "/women_products/womens-winter-boots-with-pointed-toes.jpg",
    images: ["/women_products/womens-winter-boots-with-pointed-toes.jpg", "/women_products/download-5.jpg"], // Added multiple images support for product detail view
    category: "Shoes",
    description: "Stylish ankle boots in premium leather. Block heel for comfort and versatile styling.",
    sizes: ["5", "6", "7", "8", "9", "10"],
    colors: ["Brown", "Black", "Tan"],
    rating: 4.7,
    reviews: 312,
    inStock: true,
    mode: "women",
  },
  {
    id: "20",
    name: "Denim Jacket",
    slug: "denim-jacket-women",
    price: 1899,
    originalPrice: 2499,
    discount: 24,
    image: "/women_products/13-ways-to-wear-a-denim-jacket-this-fall-2025-the-catalog-by-celine.jpg",
    images: ["/women_products/13-ways-to-wear-a-denim-jacket-this-fall-2025-the-catalog-by-celine.jpg", "/women_products/fall-outfit-inspo-aesthetic-school-slightly-oversized-denim-jacket-worn-open-over-a-fitted-black-long-sleeved-top-high-waisted-black-leggings.jpg"], // Added multiple images support for product detail view
    category: "Jackets",
    description: "Classic denim jacket with vintage wash. Timeless piece that goes with everything.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Light Blue", "Dark Blue", "Black"],
    rating: 4.8,
    reviews: 423,
    inStock: true,
    mode: "women",
  },

  // Kids' Products
  { 
    id: "21",
    name: "Cartoon T-Shirt",
    slug: "cartoon-t-shirt",
    price: 599,
    originalPrice: 899,
    discount: 33,
    image: "/kids_products/kids_product1.jpg",
    images: ["/kids_products/kids_product1.jpg", "/kids_products/kids_product13.jpg"], // Added multiple images support for product detail view
    category: "T-Shirts",
    description: "Fun cartoon print t-shirt in soft cotton. Comfortable and durable for active kids.",
    sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y", "10-11Y"],
    colors: ["Blue", "Red", "Yellow"],
    rating: 4.5,
    reviews: 234,
    inStock: true,
    mode: "kids",
  },
  {
    id: "22",
    name: "Denim Shorts",
    slug: "denim-shorts",
    price: 799,
    image: "/kids_products/kids_product6.jpg",
    images: ["/kids_products/kids_product6.jpg", "/kids_products/kids_product7.jpg"], // Added multiple images support for product detail view
    category: "Shorts",
    description: "Classic denim shorts with adjustable waist. Perfect for summer play and adventures.",
    sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y"],
    colors: ["Blue", "Black"],
    rating: 4.4,
    reviews: 167,
    inStock: true,
    mode: "kids",
  },
  {
    id: "23",
    name: "Sneakers with Lights",
    slug: "sneakers-with-lights",
    price: 1299,
    originalPrice: 1799,
    discount: 28,
    image: "/kids_products/kids_product12.jpg",
    images: ["/kids_products/kids_product12.jpg", "/kids_products/kids_product19.jpg"], // Added multiple images support for product detail view
    category: "Shoes",
    description: "Exciting light-up sneakers that flash with every step. Comfortable and fun for kids.",
    sizes: ["10", "11", "12", "13", "1", "2"],
    colors: ["Multi", "Pink", "Blue"],
    rating: 4.8,
    reviews: 412,
    inStock: true,
    mode: "kids",
  },
  {
    id: "24",
    name: "Character Backpack",
    slug: "character-backpack",
    price: 999,
    image: "/kids_products/kids_product3.jpg",
    images: ["/kids_products/kids_product3.jpg", "/kids_products/kids_product8.jpg"], // Added multiple images support for product detail view
    category: "Accessories",
    description: "Fun character backpack with padded straps. Perfect size for school or outings.",
    sizes: ["One Size"],
    colors: ["Blue", "Pink", "Green"],
    rating: 4.7,
    reviews: 298,
    inStock: true,
    mode: "kids",
  },
  {
    id: "25",
    name: "Cotton Dress",
    slug: "cotton-dress-kids",
    price: 899,
    originalPrice: 1299,
    discount: 31,
    image: "/kids_products/kids_product15.jpg",
    images: ["/kids_products/kids_product15.jpg", "/kids_products/kids_product14.jpg"], // Added multiple images support for product detail view
    category: "Dresses",
    description: "Adorable cotton dress with cute print. Comfortable and easy to wear for everyday fun.",
    sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y"],
    colors: ["Pink", "Yellow", "Blue"],
    rating: 4.6,
    reviews: 178,
    inStock: true,
    mode: "kids",
  },
  {
    id: "26",
    name: "Hoodie Set",
    slug: "hoodie-set",
    price: 1199,
    image: "/kids_products/kids_product5.jpg",
    images: ["/kids_products/kids_product5.jpg", "/kids_products/kids_product20.jpg"], // Added multiple images support for product detail view
    category: "Sets",
    description: "Matching hoodie and pants set in soft fleece. Perfect for casual wear and playtime.",
    sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y", "10-11Y"],
    colors: ["Grey", "Navy", "Black"],
    rating: 4.7,
    reviews: 203,
    inStock: true,
    mode: "kids",
  },
  {
    id: "27",
    name: "Cargo Pants",
    slug: "cargo-pants-kids",
    price: 999,
    originalPrice: 1399,
    discount: 29,
    image: "/kids_products/kids_product4.jpg",
    images: ["/kids_products/kids_product4.jpg", "/kids_products/kids_product16.jpg"], // Added multiple images support for product detail view
    category: "Pants",
    description: "Durable cargo pants with multiple pockets. Great for adventures and everyday wear.",
    sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y", "10-11Y"],
    colors: ["Khaki", "Black", "Navy"],
    rating: 4.5,
    reviews: 156,
    inStock: true,
    mode: "kids",
  },
  {
    id: "28",
    name: "Sports Jacket",
    slug: "sports-jacket-kids",
    price: 1399,
    image: "/kids_products/kids_product11.jpg",
    images: ["/kids_products/kids_product11.jpg", "/kids_products/kids_product17.jpg"], // Added multiple images support for product detail view
    category: "Jackets",
    description: "Lightweight sports jacket with hood. Perfect for outdoor activities and sports.",
    sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y", "10-11Y"],
    colors: ["Blue", "Red", "Green"],
    rating: 4.6,
    reviews: 189,
    inStock: true,
    mode: "kids",
  },
  {
    id: "29",
    name: "Swimwear Set",
    slug: "swimwear-set",
    price: 899,
    image: "/kids_products/kids_product10.jpg",
    images: ["/kids_products/kids_product10.jpg", "/kids_products/kids_product18.jpg"], // Added multiple images support for product detail view
    category: "Swimwear",
    description: "Fun and comfortable swimwear for pool and beach. Quick-drying and UV protective.",
    sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y"],
    colors: ["Blue", "Pink", "Multi"],
    rating: 4.4,
    reviews: 234,
    inStock: true,
    mode: "kids",
  },
  {
    id: "30",
    name: "School Uniform Set",
    slug: "school-uniform-set",
    price: 1499,
    image: "/kids_products/kids_product2.jpg",
    images: ["/kids_products/kids_product2.jpg", "/kids_products/kids_product9.jpg"], // Added multiple images support for product detail view
    category: "Uniforms",
    description: "Complete school uniform set with shirt and pants. Durable fabric for daily wear.",
    sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y", "10-11Y"],
    colors: ["White/Blue", "White/Grey"],
    rating: 4.7,
    reviews: 312,
    inStock: true,
    mode: "kids",
  },
]

export const categories = [
  { name: "Shirts", mode: "men" },
  { name: "Jeans", mode: "men" },
  { name: "Jackets", mode: "men" },
  { name: "Shoes", mode: "men" },
  { name: "Trousers", mode: "men" },
  { name: "Hoodies", mode: "men" },
  { name: "Blazers", mode: "men" },
  { name: "T-Shirts", mode: "men" },
  { name: "Accessories", mode: "men" },
  { name: "Dresses", mode: "women" },
  { name: "Tops", mode: "women" },
  { name: "Jeans", mode: "women" },
  { name: "Accessories", mode: "women" },
  { name: "Sweaters", mode: "women" },
  { name: "Skirts", mode: "women" },
  { name: "Jackets", mode: "women" },
  { name: "Shoes", mode: "women" },
  { name: "T-Shirts", mode: "kids" },
  { name: "Shorts", mode: "kids" },
  { name: "Shoes", mode: "kids" },
  { name: "Accessories", mode: "kids" },
  { name: "Dresses", mode: "kids" },
  { name: "Sets", mode: "kids" },
  { name: "Pants", mode: "kids" },
  { name: "Jackets", mode: "kids" },
  { name: "Swimwear", mode: "kids" },
  { name: "Uniforms", mode: "kids" },
]
